version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    expose:
      - "5432"
    networks:
      - local
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: receivableinfodb-local

networks:
  local:
    driver: bridge
